# Generated by Django 2.2.12 on 2020-05-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Tipo de Modalidade',
                'verbose_name_plural': 'Tipos de Modalidades',
            },
        ),
    ]
