# Generated by Django 2.2.12 on 2020-05-14 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jif', '0002_tipomodalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[['I', 'Individual'], ['C', 'Coletivo']], max_length=1)),
                ('tipo_modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jif.TipoModalidade', verbose_name='Tipo de Modalidade')),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
    ]
