# Generated by Django 2.2.12 on 2020-05-14 20:48

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('jif', '0003_modalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', stdimage.models.StdImageField(blank=True, upload_to='atletas')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=50, unique=True, verbose_name='RG')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('genero', models.CharField(choices=[['M', 'Masculino'], ['F', 'Femenino']], max_length=1, verbose_name='Gênero')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('tipo_sanguineo', models.CharField(blank=True, max_length=3, verbose_name='Tipo Sanguíneo')),
                ('plano_saude', models.CharField(blank=True, max_length=200, verbose_name='Plano de Saúde')),
                ('numero_carteira_sus', models.CharField(blank=True, max_length=20, verbose_name='Nº Carteira do SUS')),
                ('medicamento_controlado', models.TextField(blank=True, verbose_name='Medicamento Controlado')),
                ('alergia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
    ]
