# Generated by Django 2.2.12 on 2020-05-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jif', '0004_atleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotacaoModalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotacao_permitida', models.IntegerField(verbose_name='Lotação Permitida')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jif.Modalidade', verbose_name='Modalidade')),
            ],
            options={
                'verbose_name': 'Lotação da Modalidade',
                'verbose_name_plural': 'Lotação das Modalidades',
                'unique_together': {('modalidade', 'lotacao_permitida')},
            },
        ),
    ]
