# Generated by Django 2.2.12 on 2020-05-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jif', '0006_auto_20200515_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jif.Atleta', verbose_name='Atleta')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jif.Modalidade', verbose_name='Modalidade')),
                ('unidade_organizacional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jif.UnidadeOrganizacional', verbose_name='Unidade Organizacional')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('modalidade', 'atleta', 'unidade_organizacional')},
            },
        ),
    ]
